### PR TITLE
tiffRead reworked as wrapper for Scanimage tiff reader 

### PR DESCRIPTION
**Pull request by Selmaan**
the scanimage tiff reader is a class for reading tiffs generally, but scanimage tiffs in particular, very rapidly (~3x faster than previous code). It also has very simple methods to extract scanimage metadata for different scanimage versions, and to extract frame-specific information in a 'descriptions' field.

I've reworked tiffRead since it's integrated broadly into our code already. It should be compatable with SI2015/2016 data, but I'm not sure about older SI versions, so I've left the old code commented out below the new code in case it's needed. 

This rework should allow us to simply update our scanimagetiffreader periodically as new scanimage versions are released, instead of having to figure out a custom scheme ourselves for metadata extraction.

### CODE REVIEW

**Comment by mjlm** [comment]
Just tested the new tiffRead on my lab pc. It works and is really fast!
But does it work on mac/linux? Would be necessary for Orchestra. I'll test it now, but looking at those mex files, I guess it might not work. Does SI support linux? Perhaps there are binaries we can download.

**Comment by Selmaan** [comment]
Yes, they have binaries for mac, Linux, and windows. Maybe we can put them
all in the repo, and matlab will grab the right mex files?

**Comment by mjlm** [comment]
Yes that should work. I think mexw64 stands for mex-windows-64 so it can differentiate between the different versions. When I just tested it on linux, it complained about a missing mex file, i.e. didn't just take the windows one. Could you just add the mex files to the private folder?

**Comment by Selmaan** [comment]
Yea, I think (hope) the .m files are all the same, and all we have to do is
put all the mex files in private

**Pull request merged**
